project:
  type: website

date: 2024-07-20
lang: de

website:
  repo-url: https://github.com/uegwq/Grundbegriffe-der-Informatik
  repo-actions: [edit, issue]
  title: "Grundbegriffe der Informatik"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "2 Signale, Nachrichten, Informationen, Daten"
        contents:
        - "2 Signale, Nachrichten, Informationen, Daten/Abstraktion.md"
        - "2 Signale, Nachrichten, Informationen, Daten/Datum.md"
        - "2 Signale, Nachrichten, Informationen, Daten/Inschrift.md"
        - "2 Signale, Nachrichten, Informationen, Daten/Interpretation bzw Information.md"
        - "2 Signale, Nachrichten, Informationen, Daten/Nachricht.md"
        - "2 Signale, Nachrichten, Informationen, Daten/Signal.md"
      - section: "3 Mengen, Alphabete, Abbildungen"
        contents:
        - "3 Mengen, Alphabete, Abbildungen/Abbildung.md"
        - "3 Mengen, Alphabete, Abbildungen/Alphabet.md"
        - "3 Mengen, Alphabete, Abbildungen/Kathesisches Produkt von A und B.md"
        - "3 Mengen, Alphabete, Abbildungen/Kathesisches Produkt von M1, M2 und M3.md"
        - "3 Mengen, Alphabete, Abbildungen/Linkseindeutig.md"
        - "3 Mengen, Alphabete, Abbildungen/Linkstotal.md"
        - "3 Mengen, Alphabete, Abbildungen/Mn.md"
        - "3 Mengen, Alphabete, Abbildungen/Potenzmenge.md"
        - "3 Mengen, Alphabete, Abbildungen/Rechtseindeutig.md"
        - "3 Mengen, Alphabete, Abbildungen/Rechtstotal.md"
        - "3 Mengen, Alphabete, Abbildungen/Relation.md"
        - "3 Mengen, Alphabete, Abbildungen/Unicode als Beispiel.md"
        - "3 Mengen, Alphabete, Abbildungen/partielle Abbildung.md"
      - section: "4 Wörter"
        contents:
        - "4 Wörter/A hoch n.md"
        - "4 Wörter/Binäre Operation.md"
        - "4 Wörter/Formale Sprache.md"
        - "4 Wörter/Iterierte Konkatenation.md"
        - "4 Wörter/Konkatenation zweier Wörter.md"
        - "4 Wörter/Leeres Wort.md"
        - "4 Wörter/Wort aus einem Alphabet A.md"
      - section: "5 Aussagenlogik"
        contents:
        - "5 Aussagenlogik/Aussage.md"
        - "5 Aussagenlogik/Aussagenlogische Formel.md"
        - "5 Aussagenlogik/Aussagenlogische Konnektive.md"
        - "5 Aussagenlogik/Aussagenlogische Variablen.md"
        - "5 Aussagenlogik/Aussagenlogische Verknüpfungsmenge.md"
        - "5 Aussagenlogik/Auswertungsfunktion.md"
        - "5 Aussagenlogik/Boolesche Menge.md"
        - "5 Aussagenlogik/Boolsche Funktion.md"
        - "5 Aussagenlogik/Erfüllbare Formeln.md"
        - "5 Aussagenlogik/Interpretation einer Menge VarAl.md"
        - "5 Aussagenlogik/Menge aller Interpretationen für eine Variablenmenge V.md"
        - "5 Aussagenlogik/Modell einer Formelmenge.md"
        - "5 Aussagenlogik/Tautologie.md"
        - "5 Aussagenlogik/Äquivalente Aussagen.md"
        - "5 Aussagenlogik/Γ Tautologie zu G.md"
      - section: "7 Formale Sprachen"
        contents:
        - "7 Formale Sprachen/Konkatenation Formaler Sprachen.md"
      - section: "8 Übersetzungen und Codierungen"
        contents:
        - "8 Übersetzungen und Codierungen/Binärdarstellung.md"
        - "8 Übersetzungen und Codierungen/Codierung.md"
        - "8 Übersetzungen und Codierungen/Ganzzahlige Division mit Rest.md"
        - "8 Übersetzungen und Codierungen/Homomorphismus im Wortkontext.md"
        - "8 Übersetzungen und Codierungen/Huffman Code.md"
        - "8 Übersetzungen und Codierungen/Induktion über die Wortlänge.md"
        - "8 Übersetzungen und Codierungen/K-äre Darstellung bzw K-Äre Repräsentation.md"
        - "8 Übersetzungen und Codierungen/Komposition von Funktionen.md"
        - "8 Übersetzungen und Codierungen/Menge aller Abbildungen von A nach B.md"
        - "8 Übersetzungen und Codierungen/N_x(w), Anzahl von x in Wort w.md"
        - "8 Übersetzungen und Codierungen/Problematik - Führende Nullen.md"
        - "8 Übersetzungen und Codierungen/Präfixfreier Homomorphismus.md"
        - "8 Übersetzungen und Codierungen/Zweierkomplement von Binärzahlen.md"
        - "8 Übersetzungen und Codierungen/num(x) Dezimaldarstellung von Zahlen.md"
        - "8 Übersetzungen und Codierungen/Übersetzen.md"
        - "8 Übersetzungen und Codierungen/Übersetzung von Zahldarstellungen.md"
        - "8 Übersetzungen und Codierungen/ε-Freier Homomorphismus.md"
      - section: "9 Speicher"
        contents:
        - "9 Speicher/Auslesefunktion eines Speichers.md"
        - "9 Speicher/Bit.md"
        - "9 Speicher/Caches.md"
        - "9 Speicher/Eigenschaften des von uns definierten Speichers.md"
        - "9 Speicher/Menge aller möglichen Speicherzustände.md"
        - "9 Speicher/Schreibfunktion eines Speichers.md"
        - "9 Speicher/Speicher als Tabelle.md"
        - "9 Speicher/Speichern.md"
        - "9 Speicher/Wahlfreier Zugriff.md"
      - section: "12 Kontextfreie Grammatiken"
        contents:
        - "12 Kontextfreie Grammatiken/Ableitungsschritt in einer Grammatik.md"
        - "12 Kontextfreie Grammatiken/Aufbau einer kontextfreien Grammatik.md"
        - "12 Kontextfreie Grammatiken/Identische Abbildung auf Menge M.md"
        - "12 Kontextfreie Grammatiken/Potenz einer Relation.md"
        - "12 Kontextfreie Grammatiken/Produkt von Relationen.md"
        - "12 Kontextfreie Grammatiken/Reflexiv Transitive Hülle.md"
        - "12 Kontextfreie Grammatiken/Von einer Grammatik erzeugten Formalen Sprache.md"
      - section: "13 Prädikatenlogik"
        contents:
        - "13 Prädikatenlogik/Allgemeingültige Prädikatenlogische Formeln.md"
        - "13 Prädikatenlogik/Atomare Formeln.md"
        - "13 Prädikatenlogik/Auswertung einer Prädikatenlogischer Formel.md"
        - "13 Prädikatenlogik/Gleichheit in der Prädikatenlogik.md"
        - "13 Prädikatenlogik/Konstantensymbole.md"
        - "13 Prädikatenlogik/Modell einer prädikatenlogische Formel G.md"
        - "13 Prädikatenlogik/Prädikatenlogische Formel.md"
        - "13 Prädikatenlogik/Prädikatenlogische Interpretation.md"
        - "13 Prädikatenlogik/Prädikatenlogische Variablenbelegung.md"
        - "13 Prädikatenlogik/Signatur einer prädikatenlogischen Formel.md"
        - "13 Prädikatenlogik/Terme in der Prädikatenlogik.md"
        - "13 Prädikatenlogik/Variablenbelegungsänderungsfunktion.md"
      - section: "15 Graphen"
        contents:
        - "15 Graphen/(Einfacher) Zyklus.md"
        - "15 Graphen/Adjazente Knoten.md"
        - "15 Graphen/Baum.md"
        - "15 Graphen/Blätter eines Baumes.md"
        - "15 Graphen/Eingangs bzw Ausgangsgrad und Grad eines Knotens.md"
        - "15 Graphen/Erreichbarkeit.md"
        - "15 Graphen/Gerichteter Graph.md"
        - "15 Graphen/Graphenmarkierungen.md"
        - "15 Graphen/Kantenrelation.md"
        - "15 Graphen/M+.md"
        - "15 Graphen/Pfad.md"
        - "15 Graphen/Potenzen der Kanten eines Graphs.md"
        - "15 Graphen/Schlinge, Schlingenfrei.md"
        - "15 Graphen/Streng zusammenhängend.md"
        - "15 Graphen/Teilgraph.md"
        - "15 Graphen/Teilpfad.md"
        - "15 Graphen/Ungerichtete Graphen.md"
        - "15 Graphen/Ungerichteter Baum.md"
        - "15 Graphen/Weg.md"
        - "15 Graphen/Wiederholungsfreier Pfad.md"
        - "15 Graphen/Zu gerichtetem Graph zugehöriger ungerichteter Graph.md"
        - "15 Graphen/Zusammenhängender (ungerichteter!) Graph.md"
        - "15 Graphen/geschlossener Pfad.md"
      - section: "16 Algorhitmen in Graphen"
        contents:
        - "16 Algorhitmen in Graphen/Adjazenzliste.md"
        - "16 Algorhitmen in Graphen/Adjazenzmatrizen.md"
        - "16 Algorhitmen in Graphen/Berechnung der Ereichbarkeitsrelation.md"
        - "16 Algorhitmen in Graphen/Inzidenzenliste.md"
        - "16 Algorhitmen in Graphen/Potenzieren eines Graphen.md"
        - "16 Algorhitmen in Graphen/Wegematrix.md"
      - section: "17 Quantitative Aspekte"
        contents:
        - "17 Quantitative Aspekte/Asymptotisches bzw Größenordnungsmäßiges Wachstum.md"
        - "17 Quantitative Aspekte/Laufzeitberechnungen bei Implizit Definierten Funktionen.md"
        - "17 Quantitative Aspekte/Mastertheorem.md"
        - "17 Quantitative Aspekte/O(f).md"
        - "17 Quantitative Aspekte/Rechenzeit eines Algorithmus.md"
        - "17 Quantitative Aspekte/Speicherplatzbedarf eines Algorithmus.md"
        - "17 Quantitative Aspekte/Θ(f).md"
        - "17 Quantitative Aspekte/Ω(f).md"
      - section: "18 Endliche Automaten"
        contents:
        - "18 Endliche Automaten/Akzeptierte Formale Sprache.md"
        - "18 Endliche Automaten/Ausgabeauswertungsfunktion eines Endlichen Automatens.md"
        - "18 Endliche Automaten/Endlicher Akzeptor.md"
        - "18 Endliche Automaten/Mealy-Automat.md"
        - "18 Endliche Automaten/Moore-Automaten.md"
        - "18 Endliche Automaten/Zustandsauswertungsfunktionen eines endlichen Automaten.md"
      - section: "19 Regulärer Ausdruck"
        contents:
        - "19 Regulärer Ausdruck/Drei Sätze über die Erzeugung, Erkennung und Beschreibung formaler Sprachen.md"
        - "19 Regulärer Ausdruck/Durch regulären Ausdruck beschriebene Formale Sprache.md"
        - "19 Regulärer Ausdruck/Rechtslineare Grammatiken.md"
        - "19 Regulärer Ausdruck/Regulärer Ausdruck über Alphabet A.md"
        - "19 Regulärer Ausdruck/Stukturelle Induktion.md"
      - section: "20 Turingmaschine"
        contents:
        - "20 Turingmaschine/(haltende) Endliche Berechnung (Turingmaschine).md"
        - "20 Turingmaschine/Aufzählbare und Entscheidbare Sprache.md"
        - "20 Turingmaschine/Endkonfiguration einer Turingmaschine.md"
        - "20 Turingmaschine/Entscheidungsproblem.md"
        - "20 Turingmaschine/Konfiguration einer Turingmaschine.md"
        - "20 Turingmaschine/Turingmaschine mit Ausgabe auf dem Band.md"
        - "20 Turingmaschine/Turingmaschine.md"
        - "20 Turingmaschine/Turingmaschinenakzeptor.md"
        - "20 Turingmaschine/Unendliche Berechnung bzw nicht haltende Berechnung.md"
        - "20 Turingmaschine/Zeitkomplexität.md"
      - section: "21 Relationen"
        contents:
        - "21 Relationen/Antisymetrie.md"
        - "21 Relationen/Halbordnungen.md"
        - "21 Relationen/Hasse-Diagramm.md"
        - "21 Relationen/Totale Ordnung.md"
        - "21 Relationen/Äquivalenzklasse.md"
        - "21 Relationen/Äquivalenzrealtionen.md"
      - section: "22 MIMA"
        contents:
        - "22 MIMA/Allgemeiner Aufbau des Prozessors.md"
        - "22 MIMA/Grobstruktur der Mima, von neumann architektur.md"
        - "22 MIMA/Hauptspeicher der Mima.md"
        - "22 MIMA/Neimann Architektur vs Harvard Architektur.md"
        - "22 MIMA/Programm in einer Mima.md"
        - "22 MIMA/Wie läuft das ab mit den Befehlen.md"
        - "22 MIMA/Wie läuft die Arbeitsschritte konkret ab.md"

execute:
  freeze: true
  cache: true


bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly